// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © veryfid

//@version=4
study("Volatility Oscillator", resolution = "")
length = input(100)

// Data to use in strategy building
spike = close - open  // ayush
x = stdev(spike,length) // ayush
y = stdev(spike,length) * -1  // ayush

// plotted data that we use in strategy building
plot(spike, color = color.white, linewidth = 2, title = "Spike Linel")
p1 = plot(x, "Upper Line") 
p2 = plot(y, "Lower Line") 
